uWu_nyaa() => {
    yomu_ln(asChar(32)) # Space
    yomu_ln(asChar(33)) # !
    yomu_ln(asChar(34)) # "
    yomu_ln(asChar(35)) # #
    yomu_ln(asChar(36)) # $
    yomu_ln(asChar(37)) # %
    yomu_ln(asChar(38)) # &
    yomu_ln(asChar(39)) # '
    yomu_ln(asChar(40)) # (
    yomu_ln(asChar(41)) # )
    yomu_ln(asChar(42)) # *
    yomu_ln(asChar(43)) # +
    yomu_ln(asChar(44)) # ,
    yomu_ln(asChar(45)) # -
    yomu_ln(asChar(46)) # .
    yomu_ln(asChar(47)) # /
    yomu_ln(asChar(48)) # 0
    yomu_ln(asChar(49)) # 1
    yomu_ln(asChar(50)) # 2
    yomu_ln(asChar(51)) # 3
    yomu_ln(asChar(52)) # 4
    yomu_ln(asChar(53)) # 5
    yomu_ln(asChar(54)) # 6
    yomu_ln(asChar(55)) # 7
    yomu_ln(asChar(56)) # 8
    yomu_ln(asChar(57)) # 9
    yomu_ln(asChar(58)) # :
    yomu_ln(asChar(59)) # ;
    yomu_ln(asChar(60)) # <
    yomu_ln(asChar(61)) # =
    yomu_ln(asChar(62)) # >
    yomu_ln(asChar(63)) # ?
    yomu_ln(asChar(64)) # @
    yomu_ln(asChar(65)) # A
    yomu_ln(asChar(66)) # B
    yomu_ln(asChar(67)) # C
    yomu_ln(asChar(68)) # D
    yomu_ln(asChar(69)) # E
    yomu_ln(asChar(70)) # F
    yomu_ln(asChar(71)) # G
    yomu_ln(asChar(72)) # H
    yomu_ln(asChar(73)) # I
    yomu_ln(asChar(74)) # J
    yomu_ln(asChar(75)) # K
    yomu_ln(asChar(76)) # L
    yomu_ln(asChar(77)) # M
    yomu_ln(asChar(78)) # N
    yomu_ln(asChar(79)) # O
    yomu_ln(asChar(80)) # P
    yomu_ln(asChar(81)) # Q
    yomu_ln(asChar(82)) # R
    yomu_ln(asChar(83)) # S
    yomu_ln(asChar(84)) # T
    yomu_ln(asChar(85)) # U
    yomu_ln(asChar(86)) # V
    yomu_ln(asChar(87)) # W
    yomu_ln(asChar(88)) # X
    yomu_ln(asChar(89)) # Y
    yomu_ln(asChar(90)) # Z
    yomu_ln(asChar(91)) # [
    yomu_ln(asChar(92)) # \
    yomu_ln(asChar(93)) # ]
    yomu_ln(asChar(94)) # ^
    yomu_ln(asChar(95)) # _
    yomu_ln(asChar(96)) # `
    yomu_ln(asChar(97)) # a
    yomu_ln(asChar(98)) # b
    yomu_ln(asChar(99)) # c
    yomu_ln(asChar(100)) # d
    yomu_ln(asChar(101)) # e
    yomu_ln(asChar(102)) # f
    yomu_ln(asChar(103)) # g
    yomu_ln(asChar(104)) # h
    yomu_ln(asChar(105)) # i
    yomu_ln(asChar(106)) # j
    yomu_ln(asChar(107)) # k
    yomu_ln(asChar(108)) # l
    yomu_ln(asChar(109)) # m
    yomu_ln(asChar(110)) # n
    yomu_ln(asChar(111)) # o
    yomu_ln(asChar(112)) # p
    yomu_ln(asChar(113)) # q
    yomu_ln(asChar(114)) # r
    yomu_ln(asChar(115)) # s
    yomu_ln(asChar(116)) # t
    yomu_ln(asChar(117)) # u
    yomu_ln(asChar(118)) # v
    yomu_ln(asChar(119)) # w
    yomu_ln(asChar(120)) # x
    yomu_ln(asChar(121)) # y
    yomu_ln(asChar(122)) # z
    yomu_ln(asChar(123)) # {
    yomu_ln(asChar(124)) # |
    yomu_ln(asChar(125)) # }
    yomu_ln(asChar(126)) # ~
}