uWu_nyaa() => {
    yomu_ln(to_char(32)) # Space
    yomu_ln(to_char(33)) # !
    yomu_ln(to_char(34)) # "
    yomu_ln(to_char(35)) # #
    yomu_ln(to_char(36)) # $
    yomu_ln(to_char(37)) # %
    yomu_ln(to_char(38)) # &
    yomu_ln(to_char(39)) # '
    yomu_ln(to_char(40)) # (
    yomu_ln(to_char(41)) # )
    yomu_ln(to_char(42)) # *
    yomu_ln(to_char(43)) # +
    yomu_ln(to_char(44)) # ,
    yomu_ln(to_char(45)) # -
    yomu_ln(to_char(46)) # .
    yomu_ln(to_char(47)) # /
    yomu_ln(to_char(48)) # 0
    yomu_ln(to_char(49)) # 1
    yomu_ln(to_char(50)) # 2
    yomu_ln(to_char(51)) # 3
    yomu_ln(to_char(52)) # 4
    yomu_ln(to_char(53)) # 5
    yomu_ln(to_char(54)) # 6
    yomu_ln(to_char(55)) # 7
    yomu_ln(to_char(56)) # 8
    yomu_ln(to_char(57)) # 9
    yomu_ln(to_char(58)) # :
    yomu_ln(to_char(59)) # ;
    yomu_ln(to_char(60)) # <
    yomu_ln(to_char(61)) # =
    yomu_ln(to_char(62)) # >
    yomu_ln(to_char(63)) # ?
    yomu_ln(to_char(64)) # @
    yomu_ln(to_char(65)) # A
    yomu_ln(to_char(66)) # B
    yomu_ln(to_char(67)) # C
    yomu_ln(to_char(68)) # D
    yomu_ln(to_char(69)) # E
    yomu_ln(to_char(70)) # F
    yomu_ln(to_char(71)) # G
    yomu_ln(to_char(72)) # H
    yomu_ln(to_char(73)) # I
    yomu_ln(to_char(74)) # J
    yomu_ln(to_char(75)) # K
    yomu_ln(to_char(76)) # L
    yomu_ln(to_char(77)) # M
    yomu_ln(to_char(78)) # N
    yomu_ln(to_char(79)) # O
    yomu_ln(to_char(80)) # P
    yomu_ln(to_char(81)) # Q
    yomu_ln(to_char(82)) # R
    yomu_ln(to_char(83)) # S
    yomu_ln(to_char(84)) # T
    yomu_ln(to_char(85)) # U
    yomu_ln(to_char(86)) # V
    yomu_ln(to_char(87)) # W
    yomu_ln(to_char(88)) # X
    yomu_ln(to_char(89)) # Y
    yomu_ln(to_char(90)) # Z
    yomu_ln(to_char(91)) # [
    yomu_ln(to_char(92)) # \
    yomu_ln(to_char(93)) # ]
    yomu_ln(to_char(94)) # ^
    yomu_ln(to_char(95)) # _
    yomu_ln(to_char(96)) # `
    yomu_ln(to_char(97)) # a
    yomu_ln(to_char(98)) # b
    yomu_ln(to_char(99)) # c
    yomu_ln(to_char(100)) # d
    yomu_ln(to_char(101)) # e
    yomu_ln(to_char(102)) # f
    yomu_ln(to_char(103)) # g
    yomu_ln(to_char(104)) # h
    yomu_ln(to_char(105)) # i
    yomu_ln(to_char(106)) # j
    yomu_ln(to_char(107)) # k
    yomu_ln(to_char(108)) # l
    yomu_ln(to_char(109)) # m
    yomu_ln(to_char(110)) # n
    yomu_ln(to_char(111)) # o
    yomu_ln(to_char(112)) # p
    yomu_ln(to_char(113)) # q
    yomu_ln(to_char(114)) # r
    yomu_ln(to_char(115)) # s
    yomu_ln(to_char(116)) # t
    yomu_ln(to_char(117)) # u
    yomu_ln(to_char(118)) # v
    yomu_ln(to_char(119)) # w
    yomu_ln(to_char(120)) # x
    yomu_ln(to_char(121)) # y
    yomu_ln(to_char(122)) # z
    yomu_ln(to_char(123)) # {
    yomu_ln(to_char(124)) # |
    yomu_ln(to_char(125)) # }
    yomu_ln(to_char(126)) # ~
}