uWu_nyaa() => {
    yomu_ln(getchar(32)) # Space
    yomu_ln(getchar(33)) # !
    yomu_ln(getchar(34)) # "
    yomu_ln(getchar(35)) # #
    yomu_ln(getchar(36)) # $
    yomu_ln(getchar(37)) # %
    yomu_ln(getchar(38)) # &
    yomu_ln(getchar(39)) # '
    yomu_ln(getchar(40)) # (
    yomu_ln(getchar(41)) # )
    yomu_ln(getchar(42)) # *
    yomu_ln(getchar(43)) # +
    yomu_ln(getchar(44)) # ,
    yomu_ln(getchar(45)) # -
    yomu_ln(getchar(46)) # .
    yomu_ln(getchar(47)) # /
    yomu_ln(getchar(48)) # 0
    yomu_ln(getchar(49)) # 1
    yomu_ln(getchar(50)) # 2
    yomu_ln(getchar(51)) # 3
    yomu_ln(getchar(52)) # 4
    yomu_ln(getchar(53)) # 5
    yomu_ln(getchar(54)) # 6
    yomu_ln(getchar(55)) # 7
    yomu_ln(getchar(56)) # 8
    yomu_ln(getchar(57)) # 9
    yomu_ln(getchar(58)) # :
    yomu_ln(getchar(59)) # ;
    yomu_ln(getchar(60)) # <
    yomu_ln(getchar(61)) # =
    yomu_ln(getchar(62)) # >
    yomu_ln(getchar(63)) # ?
    yomu_ln(getchar(64)) # @
    yomu_ln(getchar(65)) # A
    yomu_ln(getchar(66)) # B
    yomu_ln(getchar(67)) # C
    yomu_ln(getchar(68)) # D
    yomu_ln(getchar(69)) # E
    yomu_ln(getchar(70)) # F
    yomu_ln(getchar(71)) # G
    yomu_ln(getchar(72)) # H
    yomu_ln(getchar(73)) # I
    yomu_ln(getchar(74)) # J
    yomu_ln(getchar(75)) # K
    yomu_ln(getchar(76)) # L
    yomu_ln(getchar(77)) # M
    yomu_ln(getchar(78)) # N
    yomu_ln(getchar(79)) # O
    yomu_ln(getchar(80)) # P
    yomu_ln(getchar(81)) # Q
    yomu_ln(getchar(82)) # R
    yomu_ln(getchar(83)) # S
    yomu_ln(getchar(84)) # T
    yomu_ln(getchar(85)) # U
    yomu_ln(getchar(86)) # V
    yomu_ln(getchar(87)) # W
    yomu_ln(getchar(88)) # X
    yomu_ln(getchar(89)) # Y
    yomu_ln(getchar(90)) # Z
    yomu_ln(getchar(91)) # [
    yomu_ln(getchar(92)) # \
    yomu_ln(getchar(93)) # ]
    yomu_ln(getchar(94)) # ^
    yomu_ln(getchar(95)) # _
    yomu_ln(getchar(96)) # `
    yomu_ln(getchar(97)) # a
    yomu_ln(getchar(98)) # b
    yomu_ln(getchar(99)) # c
    yomu_ln(getchar(100)) # d
    yomu_ln(getchar(101)) # e
    yomu_ln(getchar(102)) # f
    yomu_ln(getchar(103)) # g
    yomu_ln(getchar(104)) # h
    yomu_ln(getchar(105)) # i
    yomu_ln(getchar(106)) # j
    yomu_ln(getchar(107)) # k
    yomu_ln(getchar(108)) # l
    yomu_ln(getchar(109)) # m
    yomu_ln(getchar(110)) # n
    yomu_ln(getchar(111)) # o
    yomu_ln(getchar(112)) # p
    yomu_ln(getchar(113)) # q
    yomu_ln(getchar(114)) # r
    yomu_ln(getchar(115)) # s
    yomu_ln(getchar(116)) # t
    yomu_ln(getchar(117)) # u
    yomu_ln(getchar(118)) # v
    yomu_ln(getchar(119)) # w
    yomu_ln(getchar(120)) # x
    yomu_ln(getchar(121)) # y
    yomu_ln(getchar(122)) # z
    yomu_ln(getchar(123)) # {
    yomu_ln(getchar(124)) # |
    yomu_ln(getchar(125)) # }
    yomu_ln(getchar(126)) # ~
}